package com.naxian.pojo;

import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_type
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.compay_address
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String compayAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_introduction
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String companyIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.create_by
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_size
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String companySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_email
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String companyEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.update_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_delete
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_telno
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Long companyTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.website_company
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String websiteCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.longitude
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.pwd
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_status
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer companyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_industry
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String companyIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.x
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.xx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.xxx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String xxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_id
     *
     * @return the value of company.company_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_id
     *
     * @param companyId the value for company.company_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param companyName the value for company.company_name
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_type
     *
     * @return the value of company.company_type
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_type
     *
     * @param companyType the value for company.company_type
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.compay_address
     *
     * @return the value of company.compay_address
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompayAddress() {
        return compayAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.compay_address
     *
     * @param compayAddress the value for company.compay_address
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompayAddress(String compayAddress) {
        this.compayAddress = compayAddress == null ? null : compayAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_introduction
     *
     * @return the value of company.company_introduction
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompanyIntroduction() {
        return companyIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_introduction
     *
     * @param companyIntroduction the value for company.company_introduction
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyIntroduction(String companyIntroduction) {
        this.companyIntroduction = companyIntroduction == null ? null : companyIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.create_by
     *
     * @return the value of company.create_by
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.create_by
     *
     * @param createBy the value for company.create_by
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_size
     *
     * @return the value of company.company_size
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompanySize() {
        return companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_size
     *
     * @param companySize the value for company.company_size
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanySize(String companySize) {
        this.companySize = companySize == null ? null : companySize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_email
     *
     * @return the value of company.company_email
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_email
     *
     * @param companyEmail the value for company.company_email
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail == null ? null : companyEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.update_time
     *
     * @return the value of company.update_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.update_time
     *
     * @param updateTime the value for company.update_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_delete
     *
     * @return the value of company.is_delete
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_delete
     *
     * @param isDelete the value for company.is_delete
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_telno
     *
     * @return the value of company.company_telno
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Long getCompanyTelno() {
        return companyTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_telno
     *
     * @param companyTelno the value for company.company_telno
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyTelno(Long companyTelno) {
        this.companyTelno = companyTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.website_company
     *
     * @return the value of company.website_company
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getWebsiteCompany() {
        return websiteCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.website_company
     *
     * @param websiteCompany the value for company.website_company
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setWebsiteCompany(String websiteCompany) {
        this.websiteCompany = websiteCompany == null ? null : websiteCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.longitude
     *
     * @return the value of company.longitude
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.longitude
     *
     * @param longitude the value for company.longitude
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.pwd
     *
     * @return the value of company.pwd
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.pwd
     *
     * @param pwd the value for company.pwd
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_status
     *
     * @return the value of company.company_status
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getCompanyStatus() {
        return companyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_status
     *
     * @param companyStatus the value for company.company_status
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyStatus(Integer companyStatus) {
        this.companyStatus = companyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_industry
     *
     * @return the value of company.company_industry
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getCompanyIndustry() {
        return companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_industry
     *
     * @param companyIndustry the value for company.company_industry
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry == null ? null : companyIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.x
     *
     * @return the value of company.x
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.x
     *
     * @param x the value for company.x
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.xx
     *
     * @return the value of company.xx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.xx
     *
     * @param xx the value for company.xx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.xxx
     *
     * @return the value of company.xxx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getXxx() {
        return xxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.xxx
     *
     * @param xxx the value for company.xxx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setXxx(String xxx) {
        this.xxx = xxx == null ? null : xxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", companyId=").append(companyId);
        sb.append(", companyName=").append(companyName);
        sb.append(", companyType=").append(companyType);
        sb.append(", compayAddress=").append(compayAddress);
        sb.append(", companyIntroduction=").append(companyIntroduction);
        sb.append(", createBy=").append(createBy);
        sb.append(", companySize=").append(companySize);
        sb.append(", companyEmail=").append(companyEmail);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", companyTelno=").append(companyTelno);
        sb.append(", websiteCompany=").append(websiteCompany);
        sb.append(", longitude=").append(longitude);
        sb.append(", pwd=").append(pwd);
        sb.append(", companyStatus=").append(companyStatus);
        sb.append(", companyIndustry=").append(companyIndustry);
        sb.append(", x=").append(x);
        sb.append(", xx=").append(xx);
        sb.append(", xxx=").append(xxx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}