package com.naxian.pojo;

import java.io.Serializable;
import java.util.Date;

public class Education implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.edu_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer eduId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.edu_school
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String eduSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.edu_degree
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String eduDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.edu_sub_major
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String eduSubMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.edu_time_start
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Date eduTimeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.edu_time_end
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Date eduTimeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.resume_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.education_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer educationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.major_introduction
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String majorIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.get_certificate
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String getCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.language_skills
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String languageSkills;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.edu_id
     *
     * @return the value of education.edu_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getEduId() {
        return eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.edu_id
     *
     * @param eduId the value for education.edu_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEduId(Integer eduId) {
        this.eduId = eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.edu_school
     *
     * @return the value of education.edu_school
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getEduSchool() {
        return eduSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.edu_school
     *
     * @param eduSchool the value for education.edu_school
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEduSchool(String eduSchool) {
        this.eduSchool = eduSchool == null ? null : eduSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.edu_degree
     *
     * @return the value of education.edu_degree
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getEduDegree() {
        return eduDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.edu_degree
     *
     * @param eduDegree the value for education.edu_degree
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEduDegree(String eduDegree) {
        this.eduDegree = eduDegree == null ? null : eduDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.edu_sub_major
     *
     * @return the value of education.edu_sub_major
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getEduSubMajor() {
        return eduSubMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.edu_sub_major
     *
     * @param eduSubMajor the value for education.edu_sub_major
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEduSubMajor(String eduSubMajor) {
        this.eduSubMajor = eduSubMajor == null ? null : eduSubMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.edu_time_start
     *
     * @return the value of education.edu_time_start
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Date getEduTimeStart() {
        return eduTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.edu_time_start
     *
     * @param eduTimeStart the value for education.edu_time_start
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEduTimeStart(Date eduTimeStart) {
        this.eduTimeStart = eduTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.edu_time_end
     *
     * @return the value of education.edu_time_end
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Date getEduTimeEnd() {
        return eduTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.edu_time_end
     *
     * @param eduTimeEnd the value for education.edu_time_end
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEduTimeEnd(Date eduTimeEnd) {
        this.eduTimeEnd = eduTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.resume_id
     *
     * @return the value of education.resume_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.resume_id
     *
     * @param resumeId the value for education.resume_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.education_status
     *
     * @return the value of education.education_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getEducationStatus() {
        return educationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.education_status
     *
     * @param educationStatus the value for education.education_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setEducationStatus(Integer educationStatus) {
        this.educationStatus = educationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.major_introduction
     *
     * @return the value of education.major_introduction
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getMajorIntroduction() {
        return majorIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.major_introduction
     *
     * @param majorIntroduction the value for education.major_introduction
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setMajorIntroduction(String majorIntroduction) {
        this.majorIntroduction = majorIntroduction == null ? null : majorIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.get_certificate
     *
     * @return the value of education.get_certificate
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getGetCertificate() {
        return getCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.get_certificate
     *
     * @param getCertificate the value for education.get_certificate
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setGetCertificate(String getCertificate) {
        this.getCertificate = getCertificate == null ? null : getCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.language_skills
     *
     * @return the value of education.language_skills
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getLanguageSkills() {
        return languageSkills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.language_skills
     *
     * @param languageSkills the value for education.language_skills
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setLanguageSkills(String languageSkills) {
        this.languageSkills = languageSkills == null ? null : languageSkills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.x
     *
     * @return the value of education.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.x
     *
     * @param x the value for education.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.xx
     *
     * @return the value of education.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.xx
     *
     * @param xx the value for education.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eduId=").append(eduId);
        sb.append(", eduSchool=").append(eduSchool);
        sb.append(", eduDegree=").append(eduDegree);
        sb.append(", eduSubMajor=").append(eduSubMajor);
        sb.append(", eduTimeStart=").append(eduTimeStart);
        sb.append(", eduTimeEnd=").append(eduTimeEnd);
        sb.append(", resumeId=").append(resumeId);
        sb.append(", educationStatus=").append(educationStatus);
        sb.append(", majorIntroduction=").append(majorIntroduction);
        sb.append(", getCertificate=").append(getCertificate);
        sb.append(", languageSkills=").append(languageSkills);
        sb.append(", x=").append(x);
        sb.append(", xx=").append(xx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}