package com.naxian.pojo;

import java.io.Serializable;

public class Mycollection implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.collection_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.rec_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.mycollection_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer mycollectionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.collection_id
     *
     * @return the value of mycollection.collection_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.collection_id
     *
     * @param collectionId the value for mycollection.collection_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.rec_id
     *
     * @return the value of mycollection.rec_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.rec_id
     *
     * @param recId the value for mycollection.rec_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.per_id
     *
     * @return the value of mycollection.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.per_id
     *
     * @param perId the value for mycollection.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.mycollection_status
     *
     * @return the value of mycollection.mycollection_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getMycollectionStatus() {
        return mycollectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.mycollection_status
     *
     * @param mycollectionStatus the value for mycollection.mycollection_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setMycollectionStatus(Integer mycollectionStatus) {
        this.mycollectionStatus = mycollectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.x
     *
     * @return the value of mycollection.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.x
     *
     * @param x the value for mycollection.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.xx
     *
     * @return the value of mycollection.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.xx
     *
     * @param xx the value for mycollection.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collectionId=").append(collectionId);
        sb.append(", recId=").append(recId);
        sb.append(", perId=").append(perId);
        sb.append(", mycollectionStatus=").append(mycollectionStatus);
        sb.append(", x=").append(x);
        sb.append(", xx=").append(xx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}