package com.naxian.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PersonsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public PersonsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPerIdIsNull() {
            addCriterion("per_id is null");
            return (Criteria) this;
        }

        public Criteria andPerIdIsNotNull() {
            addCriterion("per_id is not null");
            return (Criteria) this;
        }

        public Criteria andPerIdEqualTo(Integer value) {
            addCriterion("per_id =", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotEqualTo(Integer value) {
            addCriterion("per_id <>", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThan(Integer value) {
            addCriterion("per_id >", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_id >=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThan(Integer value) {
            addCriterion("per_id <", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThanOrEqualTo(Integer value) {
            addCriterion("per_id <=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdIn(List<Integer> values) {
            addCriterion("per_id in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotIn(List<Integer> values) {
            addCriterion("per_id not in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdBetween(Integer value1, Integer value2) {
            addCriterion("per_id between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("per_id not between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPerNameIsNull() {
            addCriterion("per_name is null");
            return (Criteria) this;
        }

        public Criteria andPerNameIsNotNull() {
            addCriterion("per_name is not null");
            return (Criteria) this;
        }

        public Criteria andPerNameEqualTo(String value) {
            addCriterion("per_name =", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotEqualTo(String value) {
            addCriterion("per_name <>", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameGreaterThan(String value) {
            addCriterion("per_name >", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameGreaterThanOrEqualTo(String value) {
            addCriterion("per_name >=", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameLessThan(String value) {
            addCriterion("per_name <", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameLessThanOrEqualTo(String value) {
            addCriterion("per_name <=", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameLike(String value) {
            addCriterion("per_name like", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotLike(String value) {
            addCriterion("per_name not like", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameIn(List<String> values) {
            addCriterion("per_name in", values, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotIn(List<String> values) {
            addCriterion("per_name not in", values, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameBetween(String value1, String value2) {
            addCriterion("per_name between", value1, value2, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotBetween(String value1, String value2) {
            addCriterion("per_name not between", value1, value2, "perName");
            return (Criteria) this;
        }

        public Criteria andPerGenderIsNull() {
            addCriterion("per_gender is null");
            return (Criteria) this;
        }

        public Criteria andPerGenderIsNotNull() {
            addCriterion("per_gender is not null");
            return (Criteria) this;
        }

        public Criteria andPerGenderEqualTo(Integer value) {
            addCriterion("per_gender =", value, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderNotEqualTo(Integer value) {
            addCriterion("per_gender <>", value, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderGreaterThan(Integer value) {
            addCriterion("per_gender >", value, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_gender >=", value, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderLessThan(Integer value) {
            addCriterion("per_gender <", value, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderLessThanOrEqualTo(Integer value) {
            addCriterion("per_gender <=", value, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderIn(List<Integer> values) {
            addCriterion("per_gender in", values, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderNotIn(List<Integer> values) {
            addCriterion("per_gender not in", values, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderBetween(Integer value1, Integer value2) {
            addCriterion("per_gender between", value1, value2, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("per_gender not between", value1, value2, "perGender");
            return (Criteria) this;
        }

        public Criteria andPerBirthIsNull() {
            addCriterion("per_birth is null");
            return (Criteria) this;
        }

        public Criteria andPerBirthIsNotNull() {
            addCriterion("per_birth is not null");
            return (Criteria) this;
        }

        public Criteria andPerBirthEqualTo(Date value) {
            addCriterionForJDBCDate("per_birth =", value, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("per_birth <>", value, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthGreaterThan(Date value) {
            addCriterionForJDBCDate("per_birth >", value, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("per_birth >=", value, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthLessThan(Date value) {
            addCriterionForJDBCDate("per_birth <", value, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("per_birth <=", value, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthIn(List<Date> values) {
            addCriterionForJDBCDate("per_birth in", values, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("per_birth not in", values, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("per_birth between", value1, value2, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerBirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("per_birth not between", value1, value2, "perBirth");
            return (Criteria) this;
        }

        public Criteria andPerTelIsNull() {
            addCriterion("per_tel is null");
            return (Criteria) this;
        }

        public Criteria andPerTelIsNotNull() {
            addCriterion("per_tel is not null");
            return (Criteria) this;
        }

        public Criteria andPerTelEqualTo(Long value) {
            addCriterion("per_tel =", value, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelNotEqualTo(Long value) {
            addCriterion("per_tel <>", value, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelGreaterThan(Long value) {
            addCriterion("per_tel >", value, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelGreaterThanOrEqualTo(Long value) {
            addCriterion("per_tel >=", value, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelLessThan(Long value) {
            addCriterion("per_tel <", value, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelLessThanOrEqualTo(Long value) {
            addCriterion("per_tel <=", value, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelIn(List<Long> values) {
            addCriterion("per_tel in", values, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelNotIn(List<Long> values) {
            addCriterion("per_tel not in", values, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelBetween(Long value1, Long value2) {
            addCriterion("per_tel between", value1, value2, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerTelNotBetween(Long value1, Long value2) {
            addCriterion("per_tel not between", value1, value2, "perTel");
            return (Criteria) this;
        }

        public Criteria andPerEmailIsNull() {
            addCriterion("per_email is null");
            return (Criteria) this;
        }

        public Criteria andPerEmailIsNotNull() {
            addCriterion("per_email is not null");
            return (Criteria) this;
        }

        public Criteria andPerEmailEqualTo(String value) {
            addCriterion("per_email =", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailNotEqualTo(String value) {
            addCriterion("per_email <>", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailGreaterThan(String value) {
            addCriterion("per_email >", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailGreaterThanOrEqualTo(String value) {
            addCriterion("per_email >=", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailLessThan(String value) {
            addCriterion("per_email <", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailLessThanOrEqualTo(String value) {
            addCriterion("per_email <=", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailLike(String value) {
            addCriterion("per_email like", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailNotLike(String value) {
            addCriterion("per_email not like", value, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailIn(List<String> values) {
            addCriterion("per_email in", values, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailNotIn(List<String> values) {
            addCriterion("per_email not in", values, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailBetween(String value1, String value2) {
            addCriterion("per_email between", value1, value2, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerEmailNotBetween(String value1, String value2) {
            addCriterion("per_email not between", value1, value2, "perEmail");
            return (Criteria) this;
        }

        public Criteria andPerAddressIsNull() {
            addCriterion("per_address is null");
            return (Criteria) this;
        }

        public Criteria andPerAddressIsNotNull() {
            addCriterion("per_address is not null");
            return (Criteria) this;
        }

        public Criteria andPerAddressEqualTo(String value) {
            addCriterion("per_address =", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressNotEqualTo(String value) {
            addCriterion("per_address <>", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressGreaterThan(String value) {
            addCriterion("per_address >", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressGreaterThanOrEqualTo(String value) {
            addCriterion("per_address >=", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressLessThan(String value) {
            addCriterion("per_address <", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressLessThanOrEqualTo(String value) {
            addCriterion("per_address <=", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressLike(String value) {
            addCriterion("per_address like", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressNotLike(String value) {
            addCriterion("per_address not like", value, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressIn(List<String> values) {
            addCriterion("per_address in", values, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressNotIn(List<String> values) {
            addCriterion("per_address not in", values, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressBetween(String value1, String value2) {
            addCriterion("per_address between", value1, value2, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerAddressNotBetween(String value1, String value2) {
            addCriterion("per_address not between", value1, value2, "perAddress");
            return (Criteria) this;
        }

        public Criteria andPerImageIsNull() {
            addCriterion("per_image is null");
            return (Criteria) this;
        }

        public Criteria andPerImageIsNotNull() {
            addCriterion("per_image is not null");
            return (Criteria) this;
        }

        public Criteria andPerImageEqualTo(String value) {
            addCriterion("per_image =", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageNotEqualTo(String value) {
            addCriterion("per_image <>", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageGreaterThan(String value) {
            addCriterion("per_image >", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageGreaterThanOrEqualTo(String value) {
            addCriterion("per_image >=", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageLessThan(String value) {
            addCriterion("per_image <", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageLessThanOrEqualTo(String value) {
            addCriterion("per_image <=", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageLike(String value) {
            addCriterion("per_image like", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageNotLike(String value) {
            addCriterion("per_image not like", value, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageIn(List<String> values) {
            addCriterion("per_image in", values, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageNotIn(List<String> values) {
            addCriterion("per_image not in", values, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageBetween(String value1, String value2) {
            addCriterion("per_image between", value1, value2, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerImageNotBetween(String value1, String value2) {
            addCriterion("per_image not between", value1, value2, "perImage");
            return (Criteria) this;
        }

        public Criteria andPerStatusIsNull() {
            addCriterion("per_status is null");
            return (Criteria) this;
        }

        public Criteria andPerStatusIsNotNull() {
            addCriterion("per_status is not null");
            return (Criteria) this;
        }

        public Criteria andPerStatusEqualTo(Integer value) {
            addCriterion("per_status =", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotEqualTo(Integer value) {
            addCriterion("per_status <>", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusGreaterThan(Integer value) {
            addCriterion("per_status >", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_status >=", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLessThan(Integer value) {
            addCriterion("per_status <", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLessThanOrEqualTo(Integer value) {
            addCriterion("per_status <=", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusIn(List<Integer> values) {
            addCriterion("per_status in", values, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotIn(List<Integer> values) {
            addCriterion("per_status not in", values, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusBetween(Integer value1, Integer value2) {
            addCriterion("per_status between", value1, value2, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("per_status not between", value1, value2, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusIsNull() {
            addCriterion("person_status is null");
            return (Criteria) this;
        }

        public Criteria andPersonStatusIsNotNull() {
            addCriterion("person_status is not null");
            return (Criteria) this;
        }

        public Criteria andPersonStatusEqualTo(Integer value) {
            addCriterion("person_status =", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusNotEqualTo(Integer value) {
            addCriterion("person_status <>", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusGreaterThan(Integer value) {
            addCriterion("person_status >", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_status >=", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusLessThan(Integer value) {
            addCriterion("person_status <", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusLessThanOrEqualTo(Integer value) {
            addCriterion("person_status <=", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusIn(List<Integer> values) {
            addCriterion("person_status in", values, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusNotIn(List<Integer> values) {
            addCriterion("person_status not in", values, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusBetween(Integer value1, Integer value2) {
            addCriterion("person_status between", value1, value2, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("person_status not between", value1, value2, "personStatus");
            return (Criteria) this;
        }

        public Criteria andXxIsNull() {
            addCriterion("xx is null");
            return (Criteria) this;
        }

        public Criteria andXxIsNotNull() {
            addCriterion("xx is not null");
            return (Criteria) this;
        }

        public Criteria andXxEqualTo(String value) {
            addCriterion("xx =", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotEqualTo(String value) {
            addCriterion("xx <>", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxGreaterThan(String value) {
            addCriterion("xx >", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxGreaterThanOrEqualTo(String value) {
            addCriterion("xx >=", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxLessThan(String value) {
            addCriterion("xx <", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxLessThanOrEqualTo(String value) {
            addCriterion("xx <=", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxLike(String value) {
            addCriterion("xx like", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotLike(String value) {
            addCriterion("xx not like", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxIn(List<String> values) {
            addCriterion("xx in", values, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotIn(List<String> values) {
            addCriterion("xx not in", values, "xx");
            return (Criteria) this;
        }

        public Criteria andXxBetween(String value1, String value2) {
            addCriterion("xx between", value1, value2, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotBetween(String value1, String value2) {
            addCriterion("xx not between", value1, value2, "xx");
            return (Criteria) this;
        }

        public Criteria andXIsNull() {
            addCriterion("x is null");
            return (Criteria) this;
        }

        public Criteria andXIsNotNull() {
            addCriterion("x is not null");
            return (Criteria) this;
        }

        public Criteria andXEqualTo(String value) {
            addCriterion("x =", value, "x");
            return (Criteria) this;
        }

        public Criteria andXNotEqualTo(String value) {
            addCriterion("x <>", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThan(String value) {
            addCriterion("x >", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThanOrEqualTo(String value) {
            addCriterion("x >=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThan(String value) {
            addCriterion("x <", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThanOrEqualTo(String value) {
            addCriterion("x <=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLike(String value) {
            addCriterion("x like", value, "x");
            return (Criteria) this;
        }

        public Criteria andXNotLike(String value) {
            addCriterion("x not like", value, "x");
            return (Criteria) this;
        }

        public Criteria andXIn(List<String> values) {
            addCriterion("x in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXNotIn(List<String> values) {
            addCriterion("x not in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXBetween(String value1, String value2) {
            addCriterion("x between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andXNotBetween(String value1, String value2) {
            addCriterion("x not between", value1, value2, "x");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persons
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 09 00:57:41 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}