package com.naxian.pojo;

import java.io.Serializable;
import java.util.Date;

public class Persons implements Serializable {
    public Persons(){}
    public Persons(Integer perId, String perName, Long perTel, String perEmail, String perAddress, Integer perStatus) {
        this.perId = perId;
        this.perName = perName;
        this.perTel = perTel;
        this.perEmail = perEmail;
        this.perAddress = perAddress;
        this.perStatus = perStatus;
    }
    public Persons(Long perTel,String password){
        this.perTel = perTel;
        this.password = password;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.password
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_name
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String perName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_gender
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer perGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_birth
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Date perBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_tel
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Long perTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_email
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String perEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_address
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String perAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_image
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String perImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.per_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer perStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.person_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer personStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_id
     *
     * @return the value of persons.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_id
     *
     * @param perId the value for persons.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.password
     *
     * @return the value of persons.password
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.password
     *
     * @param password the value for persons.password
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_name
     *
     * @return the value of persons.per_name
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_name
     *
     * @param perName the value for persons.per_name
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_gender
     *
     * @return the value of persons.per_gender
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPerGender() {
        return perGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_gender
     *
     * @param perGender the value for persons.per_gender
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerGender(Integer perGender) {
        this.perGender = perGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_birth
     *
     * @return the value of persons.per_birth
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Date getPerBirth() {
        return perBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_birth
     *
     * @param perBirth the value for persons.per_birth
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerBirth(Date perBirth) {
        this.perBirth = perBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_tel
     *
     * @return the value of persons.per_tel
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Long getPerTel() {
        return perTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_tel
     *
     * @param perTel the value for persons.per_tel
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerTel(Long perTel) {
        this.perTel = perTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_email
     *
     * @return the value of persons.per_email
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getPerEmail() {
        return perEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_email
     *
     * @param perEmail the value for persons.per_email
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail == null ? null : perEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_address
     *
     * @return the value of persons.per_address
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getPerAddress() {
        return perAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_address
     *
     * @param perAddress the value for persons.per_address
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerAddress(String perAddress) {
        this.perAddress = perAddress == null ? null : perAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_image
     *
     * @return the value of persons.per_image
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getPerImage() {
        return perImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_image
     *
     * @param perImage the value for persons.per_image
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerImage(String perImage) {
        this.perImage = perImage == null ? null : perImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.per_status
     *
     * @return the value of persons.per_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPerStatus() {
        return perStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.per_status
     *
     * @param perStatus the value for persons.per_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerStatus(Integer perStatus) {
        this.perStatus = perStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.person_status
     *
     * @return the value of persons.person_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPersonStatus() {
        return personStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.person_status
     *
     * @param personStatus the value for persons.person_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPersonStatus(Integer personStatus) {
        this.personStatus = personStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.xx
     *
     * @return the value of persons.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.xx
     *
     * @param xx the value for persons.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.x
     *
     * @return the value of persons.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.x
     *
     * @param x the value for persons.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", perId=").append(perId);
        sb.append(", password=").append(password);
        sb.append(", perName=").append(perName);
        sb.append(", perGender=").append(perGender);
        sb.append(", perBirth=").append(perBirth);
        sb.append(", perTel=").append(perTel);
        sb.append(", perEmail=").append(perEmail);
        sb.append(", perAddress=").append(perAddress);
        sb.append(", perImage=").append(perImage);
        sb.append(", perStatus=").append(perStatus);
        sb.append(", personStatus=").append(personStatus);
        sb.append(", xx=").append(xx);
        sb.append(", x=").append(x);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}