package com.naxian.pojo;

import java.io.Serializable;
import java.util.Date;

public class Recruit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.company_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_job_salary
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String recJobSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_job_address
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String recJobAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_job_experience
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String recJobExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.education
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.myskill
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String myskill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.job_introduction
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String jobIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.job_demand
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String jobDemand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_create_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Date recCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_end_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Date recEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.kwd
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String kwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruit_status
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer recruitStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_per_num
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private Integer recPerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.rec_name
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String recName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.x
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.xx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recruit
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_id
     *
     * @return the value of recruit.rec_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_id
     *
     * @param recId the value for recruit.rec_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.company_id
     *
     * @return the value of recruit.company_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.company_id
     *
     * @param companyId the value for recruit.company_id
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_job_salary
     *
     * @return the value of recruit.rec_job_salary
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getRecJobSalary() {
        return recJobSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_job_salary
     *
     * @param recJobSalary the value for recruit.rec_job_salary
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecJobSalary(String recJobSalary) {
        this.recJobSalary = recJobSalary == null ? null : recJobSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_job_address
     *
     * @return the value of recruit.rec_job_address
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getRecJobAddress() {
        return recJobAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_job_address
     *
     * @param recJobAddress the value for recruit.rec_job_address
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecJobAddress(String recJobAddress) {
        this.recJobAddress = recJobAddress == null ? null : recJobAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_job_experience
     *
     * @return the value of recruit.rec_job_experience
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getRecJobExperience() {
        return recJobExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_job_experience
     *
     * @param recJobExperience the value for recruit.rec_job_experience
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecJobExperience(String recJobExperience) {
        this.recJobExperience = recJobExperience == null ? null : recJobExperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.education
     *
     * @return the value of recruit.education
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.education
     *
     * @param education the value for recruit.education
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.myskill
     *
     * @return the value of recruit.myskill
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getMyskill() {
        return myskill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.myskill
     *
     * @param myskill the value for recruit.myskill
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setMyskill(String myskill) {
        this.myskill = myskill == null ? null : myskill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.job_introduction
     *
     * @return the value of recruit.job_introduction
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getJobIntroduction() {
        return jobIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.job_introduction
     *
     * @param jobIntroduction the value for recruit.job_introduction
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setJobIntroduction(String jobIntroduction) {
        this.jobIntroduction = jobIntroduction == null ? null : jobIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.job_demand
     *
     * @return the value of recruit.job_demand
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getJobDemand() {
        return jobDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.job_demand
     *
     * @param jobDemand the value for recruit.job_demand
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setJobDemand(String jobDemand) {
        this.jobDemand = jobDemand == null ? null : jobDemand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_create_time
     *
     * @return the value of recruit.rec_create_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Date getRecCreateTime() {
        return recCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_create_time
     *
     * @param recCreateTime the value for recruit.rec_create_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecCreateTime(Date recCreateTime) {
        this.recCreateTime = recCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_end_time
     *
     * @return the value of recruit.rec_end_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Date getRecEndTime() {
        return recEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_end_time
     *
     * @param recEndTime the value for recruit.rec_end_time
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecEndTime(Date recEndTime) {
        this.recEndTime = recEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.kwd
     *
     * @return the value of recruit.kwd
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getKwd() {
        return kwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.kwd
     *
     * @param kwd the value for recruit.kwd
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setKwd(String kwd) {
        this.kwd = kwd == null ? null : kwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruit_status
     *
     * @return the value of recruit.recruit_status
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getRecruitStatus() {
        return recruitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruit_status
     *
     * @param recruitStatus the value for recruit.recruit_status
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecruitStatus(Integer recruitStatus) {
        this.recruitStatus = recruitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_per_num
     *
     * @return the value of recruit.rec_per_num
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public Integer getRecPerNum() {
        return recPerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_per_num
     *
     * @param recPerNum the value for recruit.rec_per_num
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecPerNum(Integer recPerNum) {
        this.recPerNum = recPerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.rec_name
     *
     * @return the value of recruit.rec_name
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getRecName() {
        return recName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.rec_name
     *
     * @param recName the value for recruit.rec_name
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setRecName(String recName) {
        this.recName = recName == null ? null : recName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.x
     *
     * @return the value of recruit.x
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.x
     *
     * @param x the value for recruit.x
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.xx
     *
     * @return the value of recruit.xx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.xx
     *
     * @param xx the value for recruit.xx
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recId=").append(recId);
        sb.append(", companyId=").append(companyId);
        sb.append(", recJobSalary=").append(recJobSalary);
        sb.append(", recJobAddress=").append(recJobAddress);
        sb.append(", recJobExperience=").append(recJobExperience);
        sb.append(", education=").append(education);
        sb.append(", myskill=").append(myskill);
        sb.append(", jobIntroduction=").append(jobIntroduction);
        sb.append(", jobDemand=").append(jobDemand);
        sb.append(", recCreateTime=").append(recCreateTime);
        sb.append(", recEndTime=").append(recEndTime);
        sb.append(", kwd=").append(kwd);
        sb.append(", recruitStatus=").append(recruitStatus);
        sb.append(", recPerNum=").append(recPerNum);
        sb.append(", recName=").append(recName);
        sb.append(", x=").append(x);
        sb.append(", xx=").append(xx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}