package com.naxian.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ResumesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public ResumesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andResumeIdIsNull() {
            addCriterion("resume_id is null");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNotNull() {
            addCriterion("resume_id is not null");
            return (Criteria) this;
        }

        public Criteria andResumeIdEqualTo(Integer value) {
            addCriterion("resume_id =", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotEqualTo(Integer value) {
            addCriterion("resume_id <>", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThan(Integer value) {
            addCriterion("resume_id >", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("resume_id >=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThan(Integer value) {
            addCriterion("resume_id <", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThanOrEqualTo(Integer value) {
            addCriterion("resume_id <=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIn(List<Integer> values) {
            addCriterion("resume_id in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotIn(List<Integer> values) {
            addCriterion("resume_id not in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdBetween(Integer value1, Integer value2) {
            addCriterion("resume_id between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("resume_id not between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andPerIdIsNull() {
            addCriterion("per_id is null");
            return (Criteria) this;
        }

        public Criteria andPerIdIsNotNull() {
            addCriterion("per_id is not null");
            return (Criteria) this;
        }

        public Criteria andPerIdEqualTo(Integer value) {
            addCriterion("per_id =", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotEqualTo(Integer value) {
            addCriterion("per_id <>", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThan(Integer value) {
            addCriterion("per_id >", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_id >=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThan(Integer value) {
            addCriterion("per_id <", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThanOrEqualTo(Integer value) {
            addCriterion("per_id <=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdIn(List<Integer> values) {
            addCriterion("per_id in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotIn(List<Integer> values) {
            addCriterion("per_id not in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdBetween(Integer value1, Integer value2) {
            addCriterion("per_id between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("per_id not between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andReadNumIsNull() {
            addCriterion("read_num is null");
            return (Criteria) this;
        }

        public Criteria andReadNumIsNotNull() {
            addCriterion("read_num is not null");
            return (Criteria) this;
        }

        public Criteria andReadNumEqualTo(Integer value) {
            addCriterion("read_num =", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumNotEqualTo(Integer value) {
            addCriterion("read_num <>", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumGreaterThan(Integer value) {
            addCriterion("read_num >", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_num >=", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumLessThan(Integer value) {
            addCriterion("read_num <", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumLessThanOrEqualTo(Integer value) {
            addCriterion("read_num <=", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumIn(List<Integer> values) {
            addCriterion("read_num in", values, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumNotIn(List<Integer> values) {
            addCriterion("read_num not in", values, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumBetween(Integer value1, Integer value2) {
            addCriterion("read_num between", value1, value2, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumNotBetween(Integer value1, Integer value2) {
            addCriterion("read_num not between", value1, value2, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadStatusIsNull() {
            addCriterion("read_status is null");
            return (Criteria) this;
        }

        public Criteria andReadStatusIsNotNull() {
            addCriterion("read_status is not null");
            return (Criteria) this;
        }

        public Criteria andReadStatusEqualTo(Integer value) {
            addCriterion("read_status =", value, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusNotEqualTo(Integer value) {
            addCriterion("read_status <>", value, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusGreaterThan(Integer value) {
            addCriterion("read_status >", value, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_status >=", value, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusLessThan(Integer value) {
            addCriterion("read_status <", value, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusLessThanOrEqualTo(Integer value) {
            addCriterion("read_status <=", value, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusIn(List<Integer> values) {
            addCriterion("read_status in", values, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusNotIn(List<Integer> values) {
            addCriterion("read_status not in", values, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusBetween(Integer value1, Integer value2) {
            addCriterion("read_status between", value1, value2, "readStatus");
            return (Criteria) this;
        }

        public Criteria andReadStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("read_status not between", value1, value2, "readStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIsNull() {
            addCriterion("delivery_status is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIsNotNull() {
            addCriterion("delivery_status is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusEqualTo(Integer value) {
            addCriterion("delivery_status =", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotEqualTo(Integer value) {
            addCriterion("delivery_status <>", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusGreaterThan(Integer value) {
            addCriterion("delivery_status >", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("delivery_status >=", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusLessThan(Integer value) {
            addCriterion("delivery_status <", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusLessThanOrEqualTo(Integer value) {
            addCriterion("delivery_status <=", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIn(List<Integer> values) {
            addCriterion("delivery_status in", values, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotIn(List<Integer> values) {
            addCriterion("delivery_status not in", values, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusBetween(Integer value1, Integer value2) {
            addCriterion("delivery_status between", value1, value2, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("delivery_status not between", value1, value2, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusIsNull() {
            addCriterion("person_status is null");
            return (Criteria) this;
        }

        public Criteria andPersonStatusIsNotNull() {
            addCriterion("person_status is not null");
            return (Criteria) this;
        }

        public Criteria andPersonStatusEqualTo(Integer value) {
            addCriterion("person_status =", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusNotEqualTo(Integer value) {
            addCriterion("person_status <>", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusGreaterThan(Integer value) {
            addCriterion("person_status >", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_status >=", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusLessThan(Integer value) {
            addCriterion("person_status <", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusLessThanOrEqualTo(Integer value) {
            addCriterion("person_status <=", value, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusIn(List<Integer> values) {
            addCriterion("person_status in", values, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusNotIn(List<Integer> values) {
            addCriterion("person_status not in", values, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusBetween(Integer value1, Integer value2) {
            addCriterion("person_status between", value1, value2, "personStatus");
            return (Criteria) this;
        }

        public Criteria andPersonStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("person_status not between", value1, value2, "personStatus");
            return (Criteria) this;
        }

        public Criteria andResumeNameIsNull() {
            addCriterion("resume_name is null");
            return (Criteria) this;
        }

        public Criteria andResumeNameIsNotNull() {
            addCriterion("resume_name is not null");
            return (Criteria) this;
        }

        public Criteria andResumeNameEqualTo(String value) {
            addCriterion("resume_name =", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotEqualTo(String value) {
            addCriterion("resume_name <>", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameGreaterThan(String value) {
            addCriterion("resume_name >", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameGreaterThanOrEqualTo(String value) {
            addCriterion("resume_name >=", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameLessThan(String value) {
            addCriterion("resume_name <", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameLessThanOrEqualTo(String value) {
            addCriterion("resume_name <=", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameLike(String value) {
            addCriterion("resume_name like", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotLike(String value) {
            addCriterion("resume_name not like", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameIn(List<String> values) {
            addCriterion("resume_name in", values, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotIn(List<String> values) {
            addCriterion("resume_name not in", values, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameBetween(String value1, String value2) {
            addCriterion("resume_name between", value1, value2, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotBetween(String value1, String value2) {
            addCriterion("resume_name not between", value1, value2, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeIsNull() {
            addCriterion("resume_createtime is null");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeIsNotNull() {
            addCriterion("resume_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeEqualTo(Date value) {
            addCriterionForJDBCDate("resume_createtime =", value, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("resume_createtime <>", value, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("resume_createtime >", value, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("resume_createtime >=", value, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeLessThan(Date value) {
            addCriterionForJDBCDate("resume_createtime <", value, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("resume_createtime <=", value, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeIn(List<Date> values) {
            addCriterionForJDBCDate("resume_createtime in", values, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("resume_createtime not in", values, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("resume_createtime between", value1, value2, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeCreatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("resume_createtime not between", value1, value2, "resumeCreatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeIsNull() {
            addCriterion("resume_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeIsNotNull() {
            addCriterion("resume_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeEqualTo(Date value) {
            addCriterionForJDBCDate("resume_updatetime =", value, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("resume_updatetime <>", value, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("resume_updatetime >", value, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("resume_updatetime >=", value, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeLessThan(Date value) {
            addCriterionForJDBCDate("resume_updatetime <", value, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("resume_updatetime <=", value, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeIn(List<Date> values) {
            addCriterionForJDBCDate("resume_updatetime in", values, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("resume_updatetime not in", values, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("resume_updatetime between", value1, value2, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("resume_updatetime not between", value1, value2, "resumeUpdatetime");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeIsNull() {
            addCriterion("current_income is null");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeIsNotNull() {
            addCriterion("current_income is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeEqualTo(Integer value) {
            addCriterion("current_income =", value, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeNotEqualTo(Integer value) {
            addCriterion("current_income <>", value, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeGreaterThan(Integer value) {
            addCriterion("current_income >", value, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("current_income >=", value, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeLessThan(Integer value) {
            addCriterion("current_income <", value, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeLessThanOrEqualTo(Integer value) {
            addCriterion("current_income <=", value, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeIn(List<Integer> values) {
            addCriterion("current_income in", values, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeNotIn(List<Integer> values) {
            addCriterion("current_income not in", values, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeBetween(Integer value1, Integer value2) {
            addCriterion("current_income between", value1, value2, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andCurrentIncomeNotBetween(Integer value1, Integer value2) {
            addCriterion("current_income not between", value1, value2, "currentIncome");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryIsNull() {
            addCriterion("inten_salary is null");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryIsNotNull() {
            addCriterion("inten_salary is not null");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryEqualTo(String value) {
            addCriterion("inten_salary =", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryNotEqualTo(String value) {
            addCriterion("inten_salary <>", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryGreaterThan(String value) {
            addCriterion("inten_salary >", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryGreaterThanOrEqualTo(String value) {
            addCriterion("inten_salary >=", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryLessThan(String value) {
            addCriterion("inten_salary <", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryLessThanOrEqualTo(String value) {
            addCriterion("inten_salary <=", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryLike(String value) {
            addCriterion("inten_salary like", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryNotLike(String value) {
            addCriterion("inten_salary not like", value, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryIn(List<String> values) {
            addCriterion("inten_salary in", values, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryNotIn(List<String> values) {
            addCriterion("inten_salary not in", values, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryBetween(String value1, String value2) {
            addCriterion("inten_salary between", value1, value2, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenSalaryNotBetween(String value1, String value2) {
            addCriterion("inten_salary not between", value1, value2, "intenSalary");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaIsNull() {
            addCriterion("inten_jobarea is null");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaIsNotNull() {
            addCriterion("inten_jobarea is not null");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaEqualTo(String value) {
            addCriterion("inten_jobarea =", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaNotEqualTo(String value) {
            addCriterion("inten_jobarea <>", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaGreaterThan(String value) {
            addCriterion("inten_jobarea >", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaGreaterThanOrEqualTo(String value) {
            addCriterion("inten_jobarea >=", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaLessThan(String value) {
            addCriterion("inten_jobarea <", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaLessThanOrEqualTo(String value) {
            addCriterion("inten_jobarea <=", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaLike(String value) {
            addCriterion("inten_jobarea like", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaNotLike(String value) {
            addCriterion("inten_jobarea not like", value, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaIn(List<String> values) {
            addCriterion("inten_jobarea in", values, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaNotIn(List<String> values) {
            addCriterion("inten_jobarea not in", values, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaBetween(String value1, String value2) {
            addCriterion("inten_jobarea between", value1, value2, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenJobareaNotBetween(String value1, String value2) {
            addCriterion("inten_jobarea not between", value1, value2, "intenJobarea");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeIsNull() {
            addCriterion("inten_funtype is null");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeIsNotNull() {
            addCriterion("inten_funtype is not null");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeEqualTo(String value) {
            addCriterion("inten_funtype =", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeNotEqualTo(String value) {
            addCriterion("inten_funtype <>", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeGreaterThan(String value) {
            addCriterion("inten_funtype >", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeGreaterThanOrEqualTo(String value) {
            addCriterion("inten_funtype >=", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeLessThan(String value) {
            addCriterion("inten_funtype <", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeLessThanOrEqualTo(String value) {
            addCriterion("inten_funtype <=", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeLike(String value) {
            addCriterion("inten_funtype like", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeNotLike(String value) {
            addCriterion("inten_funtype not like", value, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeIn(List<String> values) {
            addCriterion("inten_funtype in", values, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeNotIn(List<String> values) {
            addCriterion("inten_funtype not in", values, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeBetween(String value1, String value2) {
            addCriterion("inten_funtype between", value1, value2, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenFuntypeNotBetween(String value1, String value2) {
            addCriterion("inten_funtype not between", value1, value2, "intenFuntype");
            return (Criteria) this;
        }

        public Criteria andIntenPositionIsNull() {
            addCriterion("inten_position is null");
            return (Criteria) this;
        }

        public Criteria andIntenPositionIsNotNull() {
            addCriterion("inten_position is not null");
            return (Criteria) this;
        }

        public Criteria andIntenPositionEqualTo(String value) {
            addCriterion("inten_position =", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionNotEqualTo(String value) {
            addCriterion("inten_position <>", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionGreaterThan(String value) {
            addCriterion("inten_position >", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionGreaterThanOrEqualTo(String value) {
            addCriterion("inten_position >=", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionLessThan(String value) {
            addCriterion("inten_position <", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionLessThanOrEqualTo(String value) {
            addCriterion("inten_position <=", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionLike(String value) {
            addCriterion("inten_position like", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionNotLike(String value) {
            addCriterion("inten_position not like", value, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionIn(List<String> values) {
            addCriterion("inten_position in", values, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionNotIn(List<String> values) {
            addCriterion("inten_position not in", values, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionBetween(String value1, String value2) {
            addCriterion("inten_position between", value1, value2, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenPositionNotBetween(String value1, String value2) {
            addCriterion("inten_position not between", value1, value2, "intenPosition");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryIsNull() {
            addCriterion("inten_industry is null");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryIsNotNull() {
            addCriterion("inten_industry is not null");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryEqualTo(String value) {
            addCriterion("inten_industry =", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryNotEqualTo(String value) {
            addCriterion("inten_industry <>", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryGreaterThan(String value) {
            addCriterion("inten_industry >", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("inten_industry >=", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryLessThan(String value) {
            addCriterion("inten_industry <", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryLessThanOrEqualTo(String value) {
            addCriterion("inten_industry <=", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryLike(String value) {
            addCriterion("inten_industry like", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryNotLike(String value) {
            addCriterion("inten_industry not like", value, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryIn(List<String> values) {
            addCriterion("inten_industry in", values, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryNotIn(List<String> values) {
            addCriterion("inten_industry not in", values, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryBetween(String value1, String value2) {
            addCriterion("inten_industry between", value1, value2, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenIndustryNotBetween(String value1, String value2) {
            addCriterion("inten_industry not between", value1, value2, "intenIndustry");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermIsNull() {
            addCriterion("inten_jobterm is null");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermIsNotNull() {
            addCriterion("inten_jobterm is not null");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermEqualTo(String value) {
            addCriterion("inten_jobterm =", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermNotEqualTo(String value) {
            addCriterion("inten_jobterm <>", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermGreaterThan(String value) {
            addCriterion("inten_jobterm >", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermGreaterThanOrEqualTo(String value) {
            addCriterion("inten_jobterm >=", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermLessThan(String value) {
            addCriterion("inten_jobterm <", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermLessThanOrEqualTo(String value) {
            addCriterion("inten_jobterm <=", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermLike(String value) {
            addCriterion("inten_jobterm like", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermNotLike(String value) {
            addCriterion("inten_jobterm not like", value, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermIn(List<String> values) {
            addCriterion("inten_jobterm in", values, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermNotIn(List<String> values) {
            addCriterion("inten_jobterm not in", values, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermBetween(String value1, String value2) {
            addCriterion("inten_jobterm between", value1, value2, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andIntenJobtermNotBetween(String value1, String value2) {
            addCriterion("inten_jobterm not between", value1, value2, "intenJobterm");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesIsNull() {
            addCriterion("get_certificates is null");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesIsNotNull() {
            addCriterion("get_certificates is not null");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesEqualTo(String value) {
            addCriterion("get_certificates =", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesNotEqualTo(String value) {
            addCriterion("get_certificates <>", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesGreaterThan(String value) {
            addCriterion("get_certificates >", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesGreaterThanOrEqualTo(String value) {
            addCriterion("get_certificates >=", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesLessThan(String value) {
            addCriterion("get_certificates <", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesLessThanOrEqualTo(String value) {
            addCriterion("get_certificates <=", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesLike(String value) {
            addCriterion("get_certificates like", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesNotLike(String value) {
            addCriterion("get_certificates not like", value, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesIn(List<String> values) {
            addCriterion("get_certificates in", values, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesNotIn(List<String> values) {
            addCriterion("get_certificates not in", values, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesBetween(String value1, String value2) {
            addCriterion("get_certificates between", value1, value2, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andGetCertificatesNotBetween(String value1, String value2) {
            addCriterion("get_certificates not between", value1, value2, "getCertificates");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionIsNull() {
            addCriterion("language_introduction is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionIsNotNull() {
            addCriterion("language_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionEqualTo(String value) {
            addCriterion("language_introduction =", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionNotEqualTo(String value) {
            addCriterion("language_introduction <>", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionGreaterThan(String value) {
            addCriterion("language_introduction >", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("language_introduction >=", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionLessThan(String value) {
            addCriterion("language_introduction <", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionLessThanOrEqualTo(String value) {
            addCriterion("language_introduction <=", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionLike(String value) {
            addCriterion("language_introduction like", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionNotLike(String value) {
            addCriterion("language_introduction not like", value, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionIn(List<String> values) {
            addCriterion("language_introduction in", values, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionNotIn(List<String> values) {
            addCriterion("language_introduction not in", values, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionBetween(String value1, String value2) {
            addCriterion("language_introduction between", value1, value2, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andLanguageIntroductionNotBetween(String value1, String value2) {
            addCriterion("language_introduction not between", value1, value2, "languageIntroduction");
            return (Criteria) this;
        }

        public Criteria andResumesStatusIsNull() {
            addCriterion("resumes_status is null");
            return (Criteria) this;
        }

        public Criteria andResumesStatusIsNotNull() {
            addCriterion("resumes_status is not null");
            return (Criteria) this;
        }

        public Criteria andResumesStatusEqualTo(Integer value) {
            addCriterion("resumes_status =", value, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusNotEqualTo(Integer value) {
            addCriterion("resumes_status <>", value, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusGreaterThan(Integer value) {
            addCriterion("resumes_status >", value, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("resumes_status >=", value, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusLessThan(Integer value) {
            addCriterion("resumes_status <", value, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusLessThanOrEqualTo(Integer value) {
            addCriterion("resumes_status <=", value, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusIn(List<Integer> values) {
            addCriterion("resumes_status in", values, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusNotIn(List<Integer> values) {
            addCriterion("resumes_status not in", values, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusBetween(Integer value1, Integer value2) {
            addCriterion("resumes_status between", value1, value2, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andResumesStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("resumes_status not between", value1, value2, "resumesStatus");
            return (Criteria) this;
        }

        public Criteria andXIsNull() {
            addCriterion("x is null");
            return (Criteria) this;
        }

        public Criteria andXIsNotNull() {
            addCriterion("x is not null");
            return (Criteria) this;
        }

        public Criteria andXEqualTo(String value) {
            addCriterion("x =", value, "x");
            return (Criteria) this;
        }

        public Criteria andXNotEqualTo(String value) {
            addCriterion("x <>", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThan(String value) {
            addCriterion("x >", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThanOrEqualTo(String value) {
            addCriterion("x >=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThan(String value) {
            addCriterion("x <", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThanOrEqualTo(String value) {
            addCriterion("x <=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLike(String value) {
            addCriterion("x like", value, "x");
            return (Criteria) this;
        }

        public Criteria andXNotLike(String value) {
            addCriterion("x not like", value, "x");
            return (Criteria) this;
        }

        public Criteria andXIn(List<String> values) {
            addCriterion("x in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXNotIn(List<String> values) {
            addCriterion("x not in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXBetween(String value1, String value2) {
            addCriterion("x between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andXNotBetween(String value1, String value2) {
            addCriterion("x not between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andXxIsNull() {
            addCriterion("xx is null");
            return (Criteria) this;
        }

        public Criteria andXxIsNotNull() {
            addCriterion("xx is not null");
            return (Criteria) this;
        }

        public Criteria andXxEqualTo(String value) {
            addCriterion("xx =", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotEqualTo(String value) {
            addCriterion("xx <>", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxGreaterThan(String value) {
            addCriterion("xx >", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxGreaterThanOrEqualTo(String value) {
            addCriterion("xx >=", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxLessThan(String value) {
            addCriterion("xx <", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxLessThanOrEqualTo(String value) {
            addCriterion("xx <=", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxLike(String value) {
            addCriterion("xx like", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotLike(String value) {
            addCriterion("xx not like", value, "xx");
            return (Criteria) this;
        }

        public Criteria andXxIn(List<String> values) {
            addCriterion("xx in", values, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotIn(List<String> values) {
            addCriterion("xx not in", values, "xx");
            return (Criteria) this;
        }

        public Criteria andXxBetween(String value1, String value2) {
            addCriterion("xx between", value1, value2, "xx");
            return (Criteria) this;
        }

        public Criteria andXxNotBetween(String value1, String value2) {
            addCriterion("xx not between", value1, value2, "xx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resumes
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 09 00:57:41 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}