package com.naxian.pojo;

import java.io.Serializable;
import java.util.Date;

public class Resumes implements Serializable {
    //构造无参函数
    public Resumes(){}
    public Resumes(Integer resumeId,Integer perId,Integer personStatus){
        this.resumeId = resumeId;
        this.perId = perId;
        this.personStatus = personStatus;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.resume_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.read_num
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.read_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer readStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.delivery_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer deliveryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.person_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer personStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.resume_name
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String resumeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.resume_createtime
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Date resumeCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.resume_updatetime
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Date resumeUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.current_income
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer currentIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.inten_salary
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String intenSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.inten_jobarea
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String intenJobarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.inten_funtype
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String intenFuntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.inten_position
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String intenPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.inten_industry
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String intenIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.inten_jobterm
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String intenJobterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.get_certificates
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String getCertificates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.language_introduction
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String languageIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.resumes_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private Integer resumesStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.introduction_self
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private String introductionSelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.resume_id
     *
     * @return the value of resumes.resume_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.resume_id
     *
     * @param resumeId the value for resumes.resume_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.per_id
     *
     * @return the value of resumes.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.per_id
     *
     * @param perId the value for resumes.per_id
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.read_num
     *
     * @return the value of resumes.read_num
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.read_num
     *
     * @param readNum the value for resumes.read_num
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.read_status
     *
     * @return the value of resumes.read_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.read_status
     *
     * @param readStatus the value for resumes.read_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.delivery_status
     *
     * @return the value of resumes.delivery_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.delivery_status
     *
     * @param deliveryStatus the value for resumes.delivery_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setDeliveryStatus(Integer deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.person_status
     *
     * @return the value of resumes.person_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getPersonStatus() {
        return personStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.person_status
     *
     * @param personStatus the value for resumes.person_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setPersonStatus(Integer personStatus) {
        this.personStatus = personStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.resume_name
     *
     * @return the value of resumes.resume_name
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getResumeName() {
        return resumeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.resume_name
     *
     * @param resumeName the value for resumes.resume_name
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setResumeName(String resumeName) {
        this.resumeName = resumeName == null ? null : resumeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.resume_createtime
     *
     * @return the value of resumes.resume_createtime
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Date getResumeCreatetime() {
        return resumeCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.resume_createtime
     *
     * @param resumeCreatetime the value for resumes.resume_createtime
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setResumeCreatetime(Date resumeCreatetime) {
        this.resumeCreatetime = resumeCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.resume_updatetime
     *
     * @return the value of resumes.resume_updatetime
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Date getResumeUpdatetime() {
        return resumeUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.resume_updatetime
     *
     * @param resumeUpdatetime the value for resumes.resume_updatetime
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setResumeUpdatetime(Date resumeUpdatetime) {
        this.resumeUpdatetime = resumeUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.current_income
     *
     * @return the value of resumes.current_income
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getCurrentIncome() {
        return currentIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.current_income
     *
     * @param currentIncome the value for resumes.current_income
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setCurrentIncome(Integer currentIncome) {
        this.currentIncome = currentIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.inten_salary
     *
     * @return the value of resumes.inten_salary
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntenSalary() {
        return intenSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.inten_salary
     *
     * @param intenSalary the value for resumes.inten_salary
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntenSalary(String intenSalary) {
        this.intenSalary = intenSalary == null ? null : intenSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.inten_jobarea
     *
     * @return the value of resumes.inten_jobarea
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntenJobarea() {
        return intenJobarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.inten_jobarea
     *
     * @param intenJobarea the value for resumes.inten_jobarea
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntenJobarea(String intenJobarea) {
        this.intenJobarea = intenJobarea == null ? null : intenJobarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.inten_funtype
     *
     * @return the value of resumes.inten_funtype
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntenFuntype() {
        return intenFuntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.inten_funtype
     *
     * @param intenFuntype the value for resumes.inten_funtype
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntenFuntype(String intenFuntype) {
        this.intenFuntype = intenFuntype == null ? null : intenFuntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.inten_position
     *
     * @return the value of resumes.inten_position
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntenPosition() {
        return intenPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.inten_position
     *
     * @param intenPosition the value for resumes.inten_position
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntenPosition(String intenPosition) {
        this.intenPosition = intenPosition == null ? null : intenPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.inten_industry
     *
     * @return the value of resumes.inten_industry
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntenIndustry() {
        return intenIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.inten_industry
     *
     * @param intenIndustry the value for resumes.inten_industry
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntenIndustry(String intenIndustry) {
        this.intenIndustry = intenIndustry == null ? null : intenIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.inten_jobterm
     *
     * @return the value of resumes.inten_jobterm
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntenJobterm() {
        return intenJobterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.inten_jobterm
     *
     * @param intenJobterm the value for resumes.inten_jobterm
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntenJobterm(String intenJobterm) {
        this.intenJobterm = intenJobterm == null ? null : intenJobterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.get_certificates
     *
     * @return the value of resumes.get_certificates
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getGetCertificates() {
        return getCertificates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.get_certificates
     *
     * @param getCertificates the value for resumes.get_certificates
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setGetCertificates(String getCertificates) {
        this.getCertificates = getCertificates == null ? null : getCertificates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.language_introduction
     *
     * @return the value of resumes.language_introduction
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getLanguageIntroduction() {
        return languageIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.language_introduction
     *
     * @param languageIntroduction the value for resumes.language_introduction
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setLanguageIntroduction(String languageIntroduction) {
        this.languageIntroduction = languageIntroduction == null ? null : languageIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.resumes_status
     *
     * @return the value of resumes.resumes_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public Integer getResumesStatus() {
        return resumesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.resumes_status
     *
     * @param resumesStatus the value for resumes.resumes_status
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setResumesStatus(Integer resumesStatus) {
        this.resumesStatus = resumesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.x
     *
     * @return the value of resumes.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.x
     *
     * @param x the value for resumes.x
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.xx
     *
     * @return the value of resumes.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.xx
     *
     * @param xx the value for resumes.xx
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.introduction_self
     *
     * @return the value of resumes.introduction_self
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public String getIntroductionSelf() {
        return introductionSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.introduction_self
     *
     * @param introductionSelf the value for resumes.introduction_self
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    public void setIntroductionSelf(String introductionSelf) {
        this.introductionSelf = introductionSelf == null ? null : introductionSelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resumeId=").append(resumeId);
        sb.append(", perId=").append(perId);
        sb.append(", readNum=").append(readNum);
        sb.append(", readStatus=").append(readStatus);
        sb.append(", deliveryStatus=").append(deliveryStatus);
        sb.append(", personStatus=").append(personStatus);
        sb.append(", resumeName=").append(resumeName);
        sb.append(", resumeCreatetime=").append(resumeCreatetime);
        sb.append(", resumeUpdatetime=").append(resumeUpdatetime);
        sb.append(", currentIncome=").append(currentIncome);
        sb.append(", intenSalary=").append(intenSalary);
        sb.append(", intenJobarea=").append(intenJobarea);
        sb.append(", intenFuntype=").append(intenFuntype);
        sb.append(", intenPosition=").append(intenPosition);
        sb.append(", intenIndustry=").append(intenIndustry);
        sb.append(", intenJobterm=").append(intenJobterm);
        sb.append(", getCertificates=").append(getCertificates);
        sb.append(", languageIntroduction=").append(languageIntroduction);
        sb.append(", resumesStatus=").append(resumesStatus);
        sb.append(", x=").append(x);
        sb.append(", xx=").append(xx);
        sb.append(", introductionSelf=").append(introductionSelf);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}