package com.naxian.mapper;

import com.naxian.pojo.CompanyLog;
import com.naxian.pojo.CompanyLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface CompanyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int countByExample(CompanyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int deleteByExample(CompanyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int deleteByPrimaryKey(Integer loginCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int insert(CompanyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int insertSelective(CompanyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    List<CompanyLog> selectByExample(CompanyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    CompanyLog selectByPrimaryKey(Integer loginCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") CompanyLog record, @Param("example") CompanyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByExample(@Param("record") CompanyLog record, @Param("example") CompanyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByPrimaryKeySelective(CompanyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_log
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByPrimaryKey(CompanyLog record);
}