package com.naxian.mapper;

import com.naxian.pojo.Education;
import com.naxian.pojo.EducationExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int countByExample(EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByExample(EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer eduId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insert(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insertSelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    List<Education> selectByExample(EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    Education selectByPrimaryKey(Integer eduId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Education record, @Param("example") EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExample(@Param("record") Education record, @Param("example") EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKey(Education record);
}