package com.naxian.mapper;

import com.naxian.pojo.InterviewInvitation;
import com.naxian.pojo.InterviewInvitationExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface InterviewInvitationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int countByExample(InterviewInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int deleteByExample(InterviewInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int deleteByPrimaryKey(Integer invitationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int insert(InterviewInvitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int insertSelective(InterviewInvitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    List<InterviewInvitation> selectByExample(InterviewInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    InterviewInvitation selectByPrimaryKey(Integer invitationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") InterviewInvitation record, @Param("example") InterviewInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByExample(@Param("record") InterviewInvitation record, @Param("example") InterviewInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByPrimaryKeySelective(InterviewInvitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_invitation
     *
     * @mbggenerated Thu Oct 10 09:41:05 CST 2019
     */
    int updateByPrimaryKey(InterviewInvitation record);
}