package com.naxian.mapper;

import com.naxian.pojo.Mycollection;
import com.naxian.pojo.MycollectionExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MycollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int countByExample(MycollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByExample(MycollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insert(Mycollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insertSelective(Mycollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    List<Mycollection> selectByExample(MycollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    Mycollection selectByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Mycollection record, @Param("example") MycollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExample(@Param("record") Mycollection record, @Param("example") MycollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(Mycollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycollection
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKey(Mycollection record);
}