package com.naxian.mapper;

import com.naxian.pojo.Persons;
import com.naxian.pojo.PersonsExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PersonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int countByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insert(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insertSelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    List<Persons> selectByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    Persons selectByPrimaryKey(Integer perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExample(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKey(Persons record);
}