package com.naxian.mapper;

import com.naxian.pojo.Resumes;
import com.naxian.pojo.ResumesExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ResumesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int countByExample(ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByExample(ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer resumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insert(Resumes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insertSelective(Resumes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    List<Resumes> selectByExampleWithBLOBs(ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    List<Resumes> selectByExample(ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    Resumes selectByPrimaryKey(Integer resumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Resumes record, @Param("example") ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Resumes record, @Param("example") ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExample(@Param("record") Resumes record, @Param("example") ResumesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(Resumes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Resumes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resumes
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKey(Resumes record);
}