package com.naxian.mapper;

import com.naxian.pojo.Workexperience;
import com.naxian.pojo.WorkexperienceExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface WorkexperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int countByExample(WorkexperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByExample(WorkexperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer experienceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insert(Workexperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int insertSelective(Workexperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    List<Workexperience> selectByExample(WorkexperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    Workexperience selectByPrimaryKey(Integer experienceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Workexperience record, @Param("example") WorkexperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByExample(@Param("record") Workexperience record, @Param("example") WorkexperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(Workexperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workexperience
     *
     * @mbggenerated Wed Oct 09 00:57:41 CST 2019
     */
    int updateByPrimaryKey(Workexperience record);
}