# 服务器项目项目配置
server:
  servlet:
    context-path: /naxian



#数据源相关配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/twfx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root

#mybatis (mapper.xml  mapper接口)
mybatis:
  mapper-locations: classpath:com/naxian/marrper/*Mapper.xml
  type-aliases-package: com.naxian.pojo
# druid提供数据库连接池
spring:
  datasource:
    #   数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/naxian?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource

    #数据库连接池的参数配置
    # 初始化连接数量
    initial-size: 5
    # 最大连接池数量
    max-active: 30
    # 最小连接池数量
    min-idle: 5
    # 获取连接时最大等待时间，单位毫秒
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 连接保持空闲而不被驱逐的最小时间
    min-evictable-idle-time-millis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    validation-query: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-borrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    pool-prepared-statements: true
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: 50
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

    #SQL 监控平台访问的相关参数（本质是个Servlet）
    stat-view-servlet:
      login-username: admin
      login-password: 123456
      allow:
      deny:
      url-pattern: /druid/*
      enabled: true #允许启用SQL监控平台

      #需要SQL监控平台监控的数据 （本质是个Filter）
    web-stat-filter:
      url-pattern: /*
      #不需要SQL监控平台监控的数据
      exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
  #页面默认前缀目录
  mvc:
    view:
      prefix: /
      #页面默认后缀目录
      suffix: .jsp


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#日志配置

logging:
  file: d://mylog/mylog.log
  level:
    com.naxian: debug
